scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/new/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plan/", include("meal_plan.urls")),
    path(
        "", RedirectView.as_view(url=reverse_lazy("recipes_list")), name="home"
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/login/post/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagsListView,
    TagsDetailView,
    TagsCreateView,
    TagsUpdateView,
    TagsDeleteView,
)



urlpatterns = [
    path("", TagsListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagsDetailView.as_view(), name="tag_detail"),
    path("new/", TagsCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagsUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagsDeleteView.as_view(), name="tag_delete"),
]

tags/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")

tags/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from tags.models import Tag


# Create your views here.
class TagsListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    paginate_by = 6


class TagsDetailView(DetailView):
    model = Tag
    template_name = "tags/details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        return context


class TagsCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/create.html"
    fields = ["name", "author", "description", "image"]
    success_url = reverse_lazy("tags_list")


class TagsUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name", "author", "description", "image"]
    success_url = reverse_lazy("tags_list")


class TagsDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("tags_list")

tags/templates/tags/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="tag-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}

tags/templates/tags/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ tag }}"?</p>
        {{ form.as_p }}
        <div class="control">
            <button class="button">Delete</button>
        </div>
    </form>
</main>
{% endblock content %}

tags/templates/tags/edit.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
<main class="tag-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}

tags/templates/tags/list.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Scrumptious</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        <li>
          <a href="{% url 'home' %}">Scrumptious</a>
        </li>
        <li>
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="{% url 'tag_new' %}">Write a tag</a>
        </li>
      </ul>
    </nav>
  </header>
  {% block pagination %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
  {% endblock pagination %}


  {% block content %}
  <main class="recipe-grid">
    {% for tag in tag_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
      </h2>
      {% for recipe in tag.recipes.all %}
      <p>
        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
      </p>
      {% endfor %}
    </div>
    {% empty %}
    <div>
      <h1>No tags, yet</h1>
      <p>
        Would you like to
        <a href="{% url 'tag_new' %}">create</a>
        one?
      </p>
    </div>
    {% endfor %}
  </main>
  {% endblock content %}
</body>

</html>